### ISSUE TITLE
additionalHeaders not working as expected

### ISSUE THREAD

**Issue by JuBan1** [KevinnZou/compose-webview-multiplatform#37] opened 2023-11-01 14:39 UTC
The doc of `rememberWebViewState` states:

> param additionalHttpHeaders Optional, additional HTTP headers that are passed to [AccompanistWebView.loadUrl]. **Note that these headers are used for all subsequent requests of the WebView.**

It seems the bolded part isn't actually true. The headers are passed along via the initial `WebContent.Url` object, but discarded when navigating inside the webview or using `navigator.loadUrl()`.

I tried it by attaching an Authorization header to a request; the initial request worked, subsequent requests were rejected.

I can see a few options here:

1. Change the docs and use the headers only for the initial request. But that would leave us with no option to actually provide universal headers.
2. Keep the headers and apply them to every subsequent `navigator.loadUrl()` call. That would apply the headers to all requests created via the navigator, but not to requests created by the webview itself.
3. Apply these headers to **all** requests. That's probably a bit more work, on Android it would involve [overrideUrlLoading](https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)), on Cef I don't know.

My personal, related issue: I want to attach an Authorization header to all requests (if possible, only requests to a certain domain). I think at the moment this is impossible.

-----

Tested using 1.6.0 and Android, but I think the current master works the same (except that additionalHeaders don't work for desktop at all in 1.6.0).

Thanks for stepping up to build and maintain an KMP webview! :muscle:

**Comment by KevinnZou** [comment] 2023-11-02 01:28
@JuBan1 Thank you for your suggestions! After checking, I also confirmed that `additionalHttpHeaders` only works for the initial request. I apologize for any confusion caused by the comment, which was copied from the accompanist Webview. I will make sure to address this issue in the future. 

However, I am currently focused on resolving the JsBridge and other issues, so it may take some time before I can start working on this particular problem. If you are interested, you are welcome to submit a PR for the Android and iOS implementation. For the Desktop side, I think @DatL4g  would be happy to provide assistance.

**Comment by JuBan1** [comment] 2023-11-03 20:17
I think a good first step would be to figure out what the goal should be.

(1) and (2) are easy to implement, but are lacking.

For my purposes I would need at least (3), but after thinking about it a little it might be a better idea to basically implement shouldOverrideUrlLoading. That allows users to intelligently add headers to all requests but also do things like intercept certain URLs or prevent certain domains.

I'm thinking users can add an `RequestInterceptor` to `WebViewNavigator`; the interceptor is a callback which is triggered for every (GET) request and enables you do (a) allow it, (b) modify it or (c) block it. I think this is possible on Android via shouldOverrideUrlLoading, on Cef via [onBeforeBrowse](https://datl4g.github.io/KCEF/jcef/org.cef.handler/-cef-request-handler/index.html#-2022335096%2FFunctions%2F1511286446), and I guess it kinda works on [iOS too](https://stackoverflow.com/a/52313781/1038629).

**Comment by KevinnZou** [comment] 2023-11-04 00:49
I agree with you. I think `RequestInterceptor` is a great idea and I would go with this plan.

**Comment by KevinnZou** [comment] 2023-11-29 13:41
@JuBan1 Hi, I have implemented the basic feature for `RequestInterceptor` on this [branch](https://github.com/KevinnZou/compose-webview-multiplatform/tree/feature/support_request_interception). It should works well on Android and iOS, but have some problem on Desktop. Can you review it and give some suggestions? Thank you so much!

**Comment by KevinnZou** [comment] 2023-11-29 13:46
@DatL4g Could you also have a look at the Desktop implementation on this  [branch](https://github.com/KevinnZou/compose-webview-multiplatform/tree/feature/support_request_interception)? I am trying to intercept the request in `CefRequestHandler.onBeforeBrowse`. It did intercept the request but will also block future requests if it return false and reload another Url like I did in the example.

**Comment by DatL4g** [comment] 2023-11-29 14:21
Adding a `CefRequestHandler` means overriding the default `CefRequestHandler`.

We had that problem before (user-agent) and we (or I) have to reimplement the default behavior in and make setting a `CefRequestHandler` extend the default reimplementation instead of overriding.

Additionally this doesn't only break the ``onBeforeBrowse` implementation, it breaks all request handling methods.

I don't have that much time currently as I'm in a release phase right now, best would be to add it directly to KCEF so we don't have to deal with it in this library, maybe you could add a PR if you have time or we have to wait until I have time again (could be anytime in December).

**Comment by JuBan1** [comment] 2023-11-29 17:25
Hey, thanks for tackling this @KevinnZou! I have a half-finished implementation as well, and I got stuck on the desktop implementation too. So that strengthens @DatL4g's point of moving it into KCEF if possible. Unfortunately I think I'm a little out of my depth there :)

I pushed my implementation [into a PR](https://github.com/KevinnZou/compose-webview-multiplatform/pull/52/files) for inspiration.

I have had more luck with overriding `onBeforeResourceLoad` and discovered that [modifying CefRequests works fine](https://github.com/KevinnZou/compose-webview-multiplatform/pull/52/files#diff-5b086cc026c8088e98f0823c6d9feb886eb3827c6f83fa6ea456bcf94691bae4R128-R129). But cancelling a request breaks the implementation. So it's probably a dead end too.

Besides, I've discovered a few more problems:

* My initial intent was to be able to set the Authorization-header for particular websites. This works on Android, but CEF actually filters out the Authorization header (and probably a few others) if you try to set it via `setHeaderMap()`. So this isn't a multiplatform solution, and authorization management would have to be a separate feature...
* Different platforms have very different scenarios in which they trigger the request interception. On Android, `shouldOverrideUrlLoading` is only called for a few URLs but on CEF `onBeforeResourceLoad` is called for literally everything: images, css-files, etc. On iOS `decidePolicyForNavigationAction` probably has its own rules. So it's tough to find common grounds so it works well on every platform without huge differences in behavior. (For example, in my implementation I tried to [exclude non-mainframe requests for CEF](https://github.com/KevinnZou/compose-webview-multiplatform/pull/52/files#diff-5b086cc026c8088e98f0823c6d9feb886eb3827c6f83fa6ea456bcf94691bae4R118-R120))

The only thing I am happy about is the [RequestInterceptor](https://github.com/KevinnZou/compose-webview-multiplatform/pull/52/files#diff-fd00b0935563598aba0106047678573a228dd4a8a25e19eaff015d54fe114b59R3-R7) and [how it is used](https://github.com/KevinnZou/compose-webview-multiplatform/pull/52/files#diff-a813bebf40cd54f1c808563de6c725977a05335cfa08946c5ba8505442ca7d07R61-R68).

On a side note, (K)CEF provides a [CEFRequestHandlerAdapter](https://github.com/KevinnZou/compose-webview-multiplatform/pull/52/files#diff-5b086cc026c8088e98f0823c6d9feb886eb3827c6f83fa6ea456bcf94691bae4R90) that has default-implementations for all methods, meaning [you don't have to do that yourself](https://github.com/KevinnZou/compose-webview-multiplatform/compare/KevinnZou:main...KevinnZou:feature/support_request_interception?expand=1#diff-5b086cc026c8088e98f0823c6d9feb886eb3827c6f83fa6ea456bcf94691bae4R169-R188)

**Comment by KevinnZou** [comment] 2023-11-30 07:46
@JuBan1 Thank you for your great work! I really appreciate your idea for RequestResult.Modify, it eliminates the need for users to manually reload the URL. I will incorporate your ideas into my implementation, as they are extremely helpful to me.

Regarding the issues you mentioned, I will collaborate with @DatL4g to see whether the Authorization header problem can be solved. Additionally, I also observed that `shouldOverrideUrlLoading` does not intercept all URLs like `onBeforeBrowse` does. I will also work on finding a solution for this issue.

Generally, I think we should be able to support Android and iOS first. As for the Desktop side, I will attempt to address the `CefRequestHandler` issue following @DatL4g's instructions. If I am unable to do that, we will have to wait for @DatL4g to resolve it next month.

Thanks for your contribution again! I will continue to update the progress here, and you are welcome to review it.

**Comment by KevinnZou** [comment] 2023-12-02 01:29
@DatL4g I briefly looked at the implementation of `addRequestHandler` in KCEF, but I have some confusion.

> Adding a `CefRequestHandler` means overriding the default `CefRequestHandler`.
> 
> We had that problem before (user-agent) and we (or I) have to reimplement the default behavior in and make setting a `CefRequestHandler` extend the default reimplementation instead of overriding.

Can you provide more detailed instructions for this paragraph? I'm not sure where your default `CefRequestHandler` is located. Because from the [implementation](https://github.com/DatL4g/jcef/blob/85c2b766028ded582ea054d54f6107fa954f9099/java/org/cef/CefClient.java#L915) of `addRequestHandler`, it seems that `requestHandler_` is initially null, and this method only saves the handler we provide into `requestHandler_` and uses it in `onBeforeBrowse`. I haven't seen the implementation of the default `CefRequestHandler`, so I am confused about how can we extend the default reimplementation instead of overriding?

**Comment by KevinnZou** [comment] 2023-12-02 02:53
@JuBan1 Regarding `shouldOverrideUrlLoading` not called issue, I searched online but couldn't find a solution. One solution I came up with is to replace `shouldOverrideUrlLoading` with intercepting `shouldInterceptRequest`. I tested `shouldInterceptRequest` and found that it gets called for every request, including internal resource loads on the page. One possible solution is to check `request?.isForMainFrame` to decide whether to intercept, which should cover most routing interception scenarios. The main [commit](https://github.com/KevinnZou/compose-webview-multiplatform/commit/34e4c6c846c8ab0281e17c8075aaeb4880ae6124) is here. Do you have any suggestions?

**Comment by DatL4g** [comment] 2023-12-03 13:33
@KevinnZou That's right, you have to dig a bit deeper, the `CefBrowser_N.java` is doing the magic.
If we provide a `CefRequestContext` which is required for `CefRequestHandler` the `request_context_` variable is set.

The problem here is that this overrides the default behavior/methods since the `request_context_` is set to `CefRequestContext.getGlobalContext` if the `request_context_` is null, otherwise this default context is not applied.

So we basically need a extendable RequestContext class which defaults to `CefRequestContext.getGlobalContext`

**Comment by KevinnZou** [comment] 2023-12-04 14:04
@DatL4g Thanks for your explanation! I think I understood why we need an extendable RequestContext. However, I'm a bit concerned that I might make mistakes since I'm not very familiar with it. I want to ensure that the code modifications are done accurately. Thus, I would prefer to leave it to you to handle the changes when you have some free time. In the meantime, I will continue working on the JSBridge implementation. Please let me know if there's anything I can do to assist you. Thank you for your contribution again!

**Comment by JuBan1** [comment] 2023-12-06 21:15
> The main [commit](https://github.com/KevinnZou/compose-webview-multiplatform/commit/34e4c6c846c8ab0281e17c8075aaeb4880ae6124) is here. Do you have any suggestions?

I'm not sure if this mechanism makes sense for `shouldInterceptRequest`. As I understand it, `shouldInterceptRequest` is called not only for the "main" url but also for content like images, css, etc.

The request interceptor gives the impression that I can Allow/Reject/Redirect this request, but Reject/Redirect changes the webview's main url, not the request that triggered the interceptor.

It seems to me that this is ultimately confusing and not very useful.

I would say it's better to use `shouldOverrideUrlLoading` and either
* accept (and document) that the intercepted requests depend on the platform, or
* limit everything to the lowest common denominator by only intercepting main urls and maybe iframe urls (or whatever actually triggers  `shouldOverrideUrlLoading`)

**Comment by KevinnZou** [comment] 2023-12-07 01:55
@JuBan1 Thanks for your suggestions! I understand your concern, `shouldOverrideUrlLoading` should be the first choice if it can intercept all the URLs. However, it is still unclear why it can only intercept partial requests. Thus, we have to make a choice:
1. use `shouldOverrideUrlLoading` but cannot intercept all requests.
2. use `shouldInterceptRequest` but only intercept the main frame and use `stopLoading` to perform the request rejection.

In my opinion, I would prefer the second option.  For the first choice, developers are unsure which requests can be intercepted and which cannot, making it unsuitable for production use. The second option is not ideal, but it can at least intercept all requests. What do you think?

**Comment by KevinnZou** [comment] 2024-01-04 03:36
> Adding a `CefRequestHandler` means overriding the default `CefRequestHandler`.
> 
> We had that problem before (user-agent) and we (or I) have to reimplement the default behavior in and make setting a `CefRequestHandler` extend the default reimplementation instead of overriding.
> 
> Additionally this doesn't only break the ``onBeforeBrowse` implementation, it breaks all request handling methods.
> 
> I don't have that much time currently as I'm in a release phase right now, best would be to add it directly to KCEF so we don't have to deal with it in this library, maybe you could add a PR if you have time or we have to wait until I have time again (could be anytime in December).

@DatL4g  Are there any updates?

**Comment by KevinnZou** [comment] 2024-01-17 03:13
@JuBan1 I reported a [bug](https://issuetracker.google.com/issues/317432128) regarding the `shouldOverrideUrlLoading` not intercepting all requests, and received a reply from the bug tracker. They explained that it is intentional for `shouldOverrideUrlLoading` to not intercept the initial load request.

Thus, regarding the previous discussion, we may have to make a choice:
1. use `shouldOverrideUrlLoading` and make iOS and desktop also not intercept the first load request.
2. use `shouldInterceptRequest` to request all the requests.

Do you have any suggestions?

**Closed** 2024-05-19 04:03 UTC
Labels: enhancement

**Comment by KevinnZou** [comment] 2024-05-19 05:25
Hi all, I have implemented a basic interception in the latest version 1.9.8. Please follow these [instructions](https://github.com/KevinnZou/compose-webview-multiplatform?tab=readme-ov-file#request-interceptor) to conduct a test and let me know if you encounter any issues.
