### ISSUE TITLE
WebView recompositions when navigate from other tab/screen

### ISSUE THREAD

**Issue by nickfaces** [KevinnZou/compose-webview-multiplatform#53] opened 2023-11-30 04:48 UTC
There are several screens and tabs in my application. On one of the screens in the tab there is a webview. Every time you switch between screens or tablets, webview refreshes the page. I'm not sure if the problem is in the webview or in voyager navigation, or even in my code.
For the accompanist, I found a similar problem where the solution was to use rememberSaveableWebViewState
https://github.com/google/accompanist/pull/1557
However, there is no such class in your library.

**Comment by nickfaces** [comment] 2023-12-06 05:06
Thanks! 
Sorry for offtop but how  do you solve same problem when you go to another screen and then come back in your apps?

**Comment by Vaibhav2002** [comment] 2024-03-06 08:11
Hi @KevinnZou 
This problem is there even with `AnimatedContent`, my web view state is lost when switching between composables using `AnimatedContent`

This is my code
```kotlin
@Composable
fun ReaderScreen(
    url: String,
    component: ReaderComponent
) {
    val listState = rememberLazyListState()
    val readerMode by component.readerMode.collectAsState()
    val state = rememberWebViewState(url)

    DisposableEffect(Unit){
        state.webSettings.apply {
            isJavaScriptEnabled = true
            backgroundColor = Color.White
            androidWebSettings.apply {
                domStorageEnabled = true
                safeBrowsingEnabled = true
                isAlgorithmicDarkeningAllowed = true
            }
        }

        onDispose {  }
    }

    BaseScreenContent(component = component){
        AnimatedContent(
            targetState = readerMode,
            transitionSpec = { fadeIn() togetherWith fadeOut() }
        ){
            when(it){
                ReaderMode.Reader -> InAppReader(Modifier.fillMaxSize(), listState, component)
                ReaderMode.Web -> WebReader(state, Modifier.fillMaxSize())
            }
        }
    }
}
```

**Comment by KevinnZou** [comment] 2024-03-07 01:52
@nickfaces Yes, as long as the `onDispose` is called, the Webview state is lost. The only solution for this problem is to use `rememberSaveableWebViewState`. However, supporting it is challenging because iOS does not have built-in functions like `saveState` and `restoreState` for WKWebview. Therefore, we might have to seek external assistance to resolve this issue.

**Comment by nickfaces** [comment] 2024-03-11 07:44
There is an interesting thing in WKWebView https://developer.apple.com/documentation/webkit/wkwebview/3752236-interactionstate
Maybe it could help, but only for iOS 15+

**Comment by KevinnZou** [comment] 2024-03-13 03:13
@nickfaces Thanks for your suggestions! It appears that interactionState is an `NSObject`? We need to find a way to serialize and deserialize it like Android.

**Comment by nickfaces** [comment] 2024-03-13 07:40
@KevinnZou If I understand it correctly, then this may help https://developer.apple.com/documentation/foundation/nscoding

**Comment by KevinnZou** [comment] 2024-03-14 01:39
> @KevinnZou If I understand it correctly, then this may help https://developer.apple.com/documentation/foundation/nscoding

@nickfaces Thanks for your information! Yes, it works for the iOS side. However, we need to find a KMP way to handle the state save and restore which could be challenging.

**Comment by skillAndroid** [comment] 2024-04-27 07:25
Hello as I see you still did not solve the problem when navigating to another page and returning to the same page when i have web view still crushing ! Pls brother this is a big problem i think!

**Comment by grandleaf** [comment] 2024-04-27 17:19
Hello Kevinn, thank you so much for the wonderful webView implementation.  I enchanted the same problem for the state save/restore of the webView.  Without this functionality, the webView can only be displayed as static without any animation and navigation, which is a huge limitation.  I just wonder if you can elevate this issue and find a temporarily solution?  If it is not possible to make it work both for Android and iOS for now, would you please make it work for Android first, then make it work in the iOS in future release?  Thanks.

**Comment by KevinnZou** [comment] 2024-04-27 22:39
@grandleaf Thank you for your understanding. As stated earlier, the problem is caused by the tab's force recomposition, and can only be temporarily resolved by state save/restore. I've been researching state save/restore support on iOS, but haven't found a way to make it work in a multiplatform environment. I will recheck next week and update you on the progress.

**Comment by grandleaf** [comment] 2024-04-28 05:22
@KevinnZou, is it possible to provide a temporarily support for Android, then support the iOS part in the future?  The reason for this is because the recomposition happens when the WebView in a navigation or even animation.  Without a state save/restore, the usage of this component is very limited.

**Comment by KevinnZou** [comment] 2024-04-28 23:44
@grandleaf Yes, I will start working on supporting at least the Android side next month. I apologize for any inconvenience caused by this issue.

**Comment by grandleaf** [comment] 2024-04-29 15:56
@KevinnZou.  Thank you for the help.  I think the root cause might be the Single Activity design for the Composable.  Any activity will be dispose if it is not in the foreground (unnecessary IMHO).

**Comment by KevinnZou** [comment] 2024-05-04 01:30
@grandleaf I have added state save/restore functionality for Android and iOS 15+ in this pull request. It allows the webview to restore its state after recomposition. However, there may still be a flickering effect initially due to the recomposition. To resolve this issue completely, we may require official support to avoid recomposition in such situations.

**Closed** 2024-05-04 02:20 UTC
Labels: wait external fix

**Comment by grandleaf** [comment] 2024-05-04 04:48
> @grandleaf I have added state save/restore functionality for Android and iOS 15+ in this pull request. It allows the webview to restore its state after recomposition. However, there may still be a flickering effect initially due to the recomposition. To resolve this issue completely, we may require official support to avoid recomposition in such situations.

@KevinnZou.  Thank so much for your wonderful work.  I do not expect the iOS part is also be accomplished 👍 
One thing puzzled me a little bit: for such a common component, why these big companies do not even provide a basic support?

Thank you again!

**Comment by grandleaf** [comment] 2024-05-04 04:57
> @grandleaf I have added state save/restore functionality for Android and iOS 15+ in this pull request. It allows the webview to restore its state after recomposition. However, there may still be a flickering effect initially due to the recomposition. To resolve this issue completely, we may require official support to avoid recomposition in such situations.

The flicker issue is hard to solve since the WebView is too expensive to be recomposed even its states can be restored.  This might be an issue for the single activity design of the framework.  There is one approach that I found might solve this problem: simply hide the WebView.  I planned to implement my own navigation instead of using the standard way.

**Comment by Vaibhav2002** [comment] 2024-05-18 11:04
@KevinnZou The rememberSaveable overload is only for URL 
Can you also add it for HTML data, this one

```kotlin
@Composable
fun rememberWebViewStateWithHTMLData(
    data: String,
    baseUrl: String? = null,
    encoding: String = "utf-8",
    mimeType: String? = null,
    historyUrl: String? = null,
)
```

**Comment by KevinnZou** [comment] 2024-05-19 05:02
@Vaibhav2002 I don't have to look into it deeply now. But I did a quick test and it seems that Android WebView does not support restore state for HTML data. You are welcomed to submit a PR if you find a way to make it workable. Thanks!

**Comment by KevinnZou** [comment] 2024-05-21 23:55
@Vaibhav2002 Does AnimatedContent implement [SaveableStateHolder](https://developer.android.com/reference/kotlin/androidx/compose/runtime/saveable/SaveableStateHolder)? `rememberSaveableWebViewState` only works with `SaveableStateHolder`.

**Comment by Vaibhav2002** [comment] 2024-05-24 08:58
> @Vaibhav2002 Does AnimatedContent implement [SaveableStateHolder](https://developer.android.com/reference/kotlin/androidx/compose/runtime/saveable/SaveableStateHolder)? `rememberSaveableWebViewState` only works with `SaveableStateHolder`.

@KevinnZou I does not work even without Animated Content

This is my code
```kotlin
when (readerMode) {
    ReaderMode.Reader -> InAppReader(Modifier.fillMaxSize(), listState, component)
    ReaderMode.Web -> WebReader(url, Modifier.fillMaxSize())
}
```

This is my webview composable
```kotlin
@Composable
internal fun WebReader(
    url: String,
    modifier:Modifier = Modifier
) {
    val state = rememberSaveableWebViewState(url)
    val navigator = rememberWebViewNavigator()

    LaunchedEffect(url){
        navigator.loadUrl(url)
    }

    DisposableEffect(Unit){
        state.webSettings.apply {
            isJavaScriptEnabled = true
            backgroundColor = Color.White
            androidWebSettings.apply {
                domStorageEnabled = true
                safeBrowsingEnabled = true
                isAlgorithmicDarkeningAllowed = true
            }
        }

        onDispose {  }
    }


    Column(modifier = modifier) {
        if (state.loadingState !is LoadingState.Finished) {
            LinearProgressIndicator(
                modifier = Modifier.fillMaxWidth().height(3.dp),
                trackColor = MaterialTheme.colorScheme.surface,
                color = LocalContentColor.current
            )
        }
        WebView(
            state = state,
            navigator = navigator,
            modifier = Modifier.fillMaxSize().navigationBarsPadding()
        )
    }
}
```

**Comment by KevinnZou** [comment] 2024-05-24 14:52
@Vaibhav2002 `rememberSavable` only works with `SaveableStateHolder`, you can check this [sample](https://github.com/KevinnZou/compose-webview-multiplatform/blob/3767b3bf321c45a4d68200ed332845391fda4144/sample/shared/src/commonMain/kotlin/com/kevinnzou/sample/navigation/CustomNavigationSample.kt#L42) for reference.

**Comment by Vaibhav2002** [comment] 2024-05-26 05:48
@KevinnZou this works, but there is a blink and my web view scroll state is lost
Also this `SaveableStateHolder` does not work when WebView is a part of a LazyColumn Item.
